### PR TITLE
Added docurl to index

### PR DESCRIPTION
**Pull request by smithrm941**
After reading your response to my issue over and digging in more, I was able to figure out getting the docurl into the index. I figured it could be useful for others.

Rhonda

### CODE REVIEW

**Comment by smithrm941** [comment]
@mattporritt I fixed the CI failures. Would you now review this PR? Thanks.

**Comment by mattporritt** [comment]
Hi,
Are you able to provide some rationale/ info for this PR? I can see what is doing, I’d like to understand more about why it is required. As discussed in the issue, from the Moodle perspective storing a doc URL in the index is not required as it is generated in Moodle on retrieval.

Thanks.

**Comment by hosungsmsft** [comment]
Hi Matt,

Rhonda was an apprentice at our team and her project was to create an experimental Moodle bot utilizing Azure services (like Azure Bot Framework, LUIS, …). She wanted to demonstrate the bot's search capability (like you did last year with Amazon Lex) and used this Moodle Azure Search plugin. She wanted to allow the chat user to click any search result to navigate to the corresponding Moodle page. We couldn't find web services defined for the Moodle Azure Search plugin, so we couldn't use something like [this](https://github.com/catalyst/moodle-search_elastic/blob/master/classes/document.php#L233) as in the Moodle Elastic Search plugin. So she went ahead and added the docurl field in this Moodle Azure Search plugin, resulting in this PR. Her apprenticeship ended last week, so I'm not sure if she'll be following up on this, but just giving you some context. We would have liked better if the docurl field was available in web services like in the Moodle Elastic Search plugin, and actually wondering if the web service support will be available on this plugin as well sometime in the future?

Thanks,
Hosung

**Comment by smithrm941** [comment]
@mattporritt I should also mention that this documentation for using Azure Search in bots mentions that it is very dependent on the index to display results so I figured that people making similar Moodle bots would want the docurl in the index: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-search-azure?view=azure-bot-service-3.0

**Comment by mattporritt** [comment]
Thanks for your contribution!
The Moodle plugin directory will be updated in the next couple of days.

**Pull request merged**
